server:
  port: 8080
  servlet:
    context-path: /social

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: host
    username: username
    password: password
    port: port
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
